version: '3.8'

services:
  api01: &api
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: api01
    environment:
      DB_HOST: rinha
      DB_USER: admin
      DB_PASS: 123
      DB_PORT: 5432
      DB_DATABASE: rinha
      DB_SCHEMA: public
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "210MB"
    restart: always

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

  db:
    image: postgres:14.6
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=2096 -c synchronous_commit=0 -c full_page_writes=0 -c fsync=off -c check_function_bodies=false
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "90MB"