spring:
#  profiles.active: local
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.database}?currentSchema=${db.schema}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  error:
    include-message:

db:
  host: ${DB_HOST}
  username: ${DB_USER}
  password: ${DB_PASS}
  port: ${DB_PORT}
  database: ${DB_DATABASE}
  schema: ${DB_SCHEMA}